-- Run this script and run the migration: safe mode

create TABLE "public"."transaction" (
	"id" int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"createdAt" int8 NULL,
	"updatedAt" int8 NULL,
	"timestamp" numeric,
	"amount" numeric,
	"currency" varchar(32),
	"receiver" int8 NOT NULL,
	"payer" int8 NOT NULL,
	"order" int8
);

alter table "public"."account"
ADD COLUMN "accountType" varchar(32) NULL,
ADD COLUMN "bankCardAccountName" text NULL,
ADD COLUMN "bankCardNumber" text NULL,
ADD COLUMN "bankCardExpiryDateMonth" int4 NULL,
ADD COLUMN "bankCardExpiryDateYear" int8 NULL;

alter table "public"."order"
ADD COLUMN "orderAcceptanceStatus" text NULL;
update "public"."order"
set "orderAcceptanceStatus" = 'pending'
where "restaurantAcceptanceStatus" = 'pending';
update "public"."order"
set "orderAcceptanceStatus" = 'accepted'
where "restaurantAcceptanceStatus" = 'accepted';
update "public"."order"
set "orderAcceptanceStatus" = 'rejected'
where "restaurantAcceptanceStatus" = 'rejected';

alter table "public"."discount"
DROP COLUMN "percentage";
alter table "public"."discount"
ADD COLUMN "value" numeric NULL,
ADD COLUMN "discountType" text NULL,
ADD COLUMN "linkedWalletAddress" text NULL DEFAULT '';
